# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 996de55d7f154c0f1df3c34a2333e3881f15affe5f53594096e42ab4d0db98ccec15a53284c7a8262ddf3630808824882261379820bd531d618d28d99de5815a

test:
  secret_key_base: 33d463611e64244cc1b304db3c5188fcfa0dabb59f7a16949d346cf1e420dd8a2ff2378610fabb602980c98e549a9fb3339f59360a6cbb19a18ffbff2ec71ddd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
